---
abstract: Perl interface to zlib/zlib-ng compression libraries
author:
  - Paul Marquess <pmqs@cpan.org>
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Compress-Raw-Zlib
no_index:
  directory:
    - t
    - inc
    - t
    - private
resources:
  bugtracker: https://github.com/pmqs/Compress-Raw-Zlib/issues
  homepage: https://github.com/pmqs/Compress-Raw-Zlib
  repository: git://github.com/pmqs/Compress-Raw-Zlib.git
version: '2.212'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
